import React, { useEffect, useState } from 'react'
import AppointmentDetailed from './AppointmentDetailed';
import { getDoctorAndClinic } from '../../Services/DoctorService';
import { DoctorAndClinic } from '../../types/appointment';

interface Props {
  doctorId:number;

  date: Date;

};
//clinic generated by doctor id! then with the clinic id generate its name and everything
const AppointmentSimple = (props: Props) => {

      const [isDetailedOpen, setDetailedListOpen] = useState(false);

      const [doctorAncClinic, setDoctorAndClinic] = useState<DoctorAndClinic | undefined>();

      const formatDate = (date: Date) => {
  return date.toLocaleString('en-GB', {
    day: '2-digit',
    month: 'short', // e.g., Dec
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZone: 'Europe/Bucharest'
  }).replace(',', ''); // remove the comma between date and time
};

useEffect(() => {
  const fetchDoctorAndClinic = async () => {
    if (props.doctorId) {  
      try {
     
        const doctorAncClinic = await getDoctorAndClinic(props.doctorId);
          if (doctorAncClinic!=undefined)
        setDoctorAndClinic(doctorAncClinic); 
        console.log("doctor and clinic:"+doctorAncClinic);
      } catch (error) {
        console.error("Error fetching doctor and clinic:", error);
      }
    }
  };
 fetchDoctorAndClinic();
}, [props.doctorId] )
      
  return (
    <>
   
      <div className="flex w-full items-center justify-between rounded-lg bg-slate-100 px-4 py-3 shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center gap-2 md:gap-32">
          <p className="font-medium text-slate-900">Doctor: {doctorAncClinic?.doctorName}</p>
          <p className="text-sm text-slate-600">Clinic: {doctorAncClinic?.clinicName}</p>
          <p className="text-sm text-slate-700">Date: {  formatDate( props.date)}</p>
        </div>

        <button
          className="btn btn-sm btn-outline"
          onClick={() => setDetailedListOpen(true)} 
        >
          Details
        </button>
      </div>


      <AppointmentDetailed
        componentVisible={isDetailedOpen}
        onClose={() => setDetailedListOpen(false)}   
      />
    </>
  );
}

export default AppointmentSimple